<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8" />
<meta name='description' content='{{site_description}}' />
<meta name='keywords' content='' />
<meta name="author" content='{{author}}' />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />

<title>{{#title}} {{title}} | {{/title}}{{site_title}}</title>

<link rel="shortcut icon" href="imgs/favicon.ico" />

<link rel="stylesheet" media="screen, projection" href="{{theme_dir}}/css/style.css" />

</head>

<header>
    <a class="logo" href="/">Amily Pearson</a>
    <nav>
        <ul>
            <li>
                <a href="/about">about</a>
            </li>

        </ul>
    </nav>
</header>
