<footer role="contentinfo">
<p>Created by Stephen Lovell</p>

<p>&copy; {{current_year}}</p>

</footer>

{{news_cache}}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script> 
<script src="{{theme_dir}}/js/fixie.min.js"></script> 
<script src="{{theme_dir}}/js/moment.min.js"></script> 
<script src="{{theme_dir}}/js/jq.tweet.min.js"></script> 
<script src="{{theme_dir}}/js/bundle.js"></script> 
</body>
</html>