<!DOCTYPE html> 
<html lang="en">
<head>

<meta charset="utf-8" />
<meta name='description' content='' />
<meta name='keywords' content='' />
<meta name="author" content="Stephen Lovell" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />

<title>stephen creates</title>

<link rel="shortcut icon" href="imgs/favicon.ico" />

<!--[if ! lte IE 6]><!-->
<link rel="stylesheet" media="screen, projection" href="{{theme_dir}}/css/style.css" />


<!--<![endif]-->

<!--[if lte IE 6]>
<link rel="stylesheet" media="screen, projection" href="http://universal-ie6-css.googlecode.com/files/ie6.1.1b.css">
<![endif]-->

<!-- enable HTML5 elements in IE7+8 -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<script type="text/javascript" src="http://use.typekit.com/mko1ywr.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
	
</head>