<?php



define('PATH', 'inc/');

class Loader { 

/////////////////////////////////////
//  PROPERTIES
/////////////////////////////////////

protected $view_paths 	= array();
     
    
/////////////////////////////////////
//  METHODS	
/////////////////////////////////////
    
	

	
	public function view($view) {
	
	
		$this->view = $view;
		return $view;
	
	}
	
	
	private function load() {
	
		echo $this->view;
	
	)
}


$this->load =& load();


echo $this->load;


