<!DOCTYPE html> 
<html lang="en">
<head>

<meta charset="utf-8" />
<meta name='description' content='' />
<meta name='keywords' content='' />
<meta name="author" content="" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />

<title>Title Here</title>

<link rel="shortcut icon" href="imgs/favicon.ico" />

<link rel="stylesheet" media="screen, projection" href="{{theme_dir}}/css/style.css" />
	
</head>